### ISSUE TITLE
Package Requirements Looks Inconsistent

### ISSUE THREAD

**Issue by daskol** [jax-ml/ml_dtypes#155]
Package distribution dependencies [`project.dependencies`][1] requires NumPy 1.x while build stage requires NumPy 2.x in [`build-system.requires`][2]. Is it a typo? Are actual build deps the following?

```toml
[build-system]
requires = [
    # TODO(phawkins): update this to 2.0.0 after its release.
    "numpy>=1.26.0",
    "setuptools~=68.1.0",
]
```

[1]: https://github.com/jax-ml/ml_dtypes/blob/v0.4.0/pyproject.toml#L19-L23
[2]: https://github.com/jax-ml/ml_dtypes/blob/v0.4.0/pyproject.toml#L52
